services:
    _defaults:
        autowire: true
        bind:
            $kernelProjectDir: '%kernel.project_dir%'

    App\Controller\:
        resource: '../../src/Controller'
        public: true
