conditions:
    path: /conditions
    controller: App\Controller\Meteo\ConditionsController

lastTenDays:
    path: /lastTenDays
    controller: App\Controller\Meteo\LastTenDaysController

lastTwoDays:
    path: /lastTwoDays
    controller: App\Controller\Meteo\LastTwoDaysController
