version: '3.5'

services:
    nginx:
        ports:
            - "80:80"
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        volumes:
            - ../public:/var/www/html/public
            - ./nginx/config/vhost.nginx:/etc/nginx/conf.d/default.conf:ro
        restart: "no"

    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
            args:
                XDEBUG_REMOTE_HOST: "${XDEBUG_REMOTE_HOST:-172.17.0.1}"
                XDEBUG_REMOTE_PORT: "${XDEBUG_REMOTE_PORT:-9000}"
                UID: "${DOCKER_UID}"
                TZ: "${TZ}"
        env_file:
            - .env
        volumes:
            - ..:/var/www/html
        restart: "no"
